#!/bin/bash

outdir='icons'

rm -Rf ./$outdir

mkdir $outdir/
mkdir $outdir/large/
mkdir $outdir/medium/
mkdir $outdir/small/

./extract

for file in $outdir/*.blp; do
	filename=`basename $file | sed 's/\\.blp//'`
	blp2totga $file | tgatoppm | pnmtopng -alpha blp.large.alpha -compression 9 > $outdir/large/$filename.png
	blp2totga $file | tgatoppm | pnmscale -width=36 -height=36 | pnmtopng -alpha blp.medium.alpha -compression 9 > $outdir/medium/${filename}.png
	blp2totga $file | tgatoppm | pnmscale -width=18 -height=18 | pnmtopng -alpha blp.small.alpha -compression 9 > $outdir/small/${filename}.png
	rm $file
done
